# pre-class

Make sure you commit this often with meaningfull messages. 


### Getting Started

We will work with the dataset called [gapminder](https://github.com/jennybc/gapminder), this is a cleaned up version from [Gapminder Data](http://www.gapminder.org/data/). Gapminder contains a lot of great data on all of the nations of the world. We first need to install the gapminder package in R. 

```{R echo=FALSE, message=FALSE, warning=FALSE}
setwd("~/Dropbox (Brown)/brown/cursos/3ro/r/pre-class-work-2018-pablogarriga/Week 03")  # change working directory to the current folder
# install.packages("gapminder")
library(gapminder)
library(dplyr)
gapminder
```

### Pre-Class Problems

Use **dplyr** functions to address the following questions:

1. How many unique countries are represented per continent?
```{R echo=TRUE, message=FALSE, warning=FALSE}
gapminder %>%
  group_by(continent) %>% 
  summarise(unique_ctry=n_distinct(country))
```

2. Which European nation had the lowest GDP per capita in 1997?
```{R echo=TRUE, message=FALSE, warning=FALSE}
gapminder %>%
  filter(continent=="Europe" & year==1997) %>%
  arrange(gdpPercap) %>%
  select(country, gdpPercap) %>%
  head()
```

3. According to the data available, what was the average life expectancy across each continent in the 1980s?
```{R echo=TRUE, message=FALSE, warning=FALSE}
gapminder %>%
  group_by(continent) %>%
  filter(year>=1980 & year<=1989) %>%
  summarise(avg_lifeExp=mean(lifeExp), sd_lifeExp=sd(lifeExp))
```

4. What 5 countries have the highest total GDP over all years combined?
```{R echo=TRUE, message=FALSE, warning=FALSE}
gapminder %>%
  group_by(country) %>%
  mutate(gdp=gdpPercap*pop) %>%
  summarise(total_gdp=sum(gdp)) %>%
  arrange(desc(total_gdp)) %>%
  select(country, total_gdp) %>%
  head(5)
```

5. What countries and years had life expectancies of _at least_ 80 years? _N.b. only output the columns of interest: country, life expectancy and year (in that order)._
```{R echo=TRUE, message=FALSE, warning=FALSE}
# I build the list of countries that meet the criteria and save it as a new dataframe
lifeExp_80=gapminder %>%
  filter(lifeExp>=80) %>%
  select(country, lifeExp, year)
# I find how many rows the dataframe has
nrows=nrow(lifeExp_80)
# I print the whole dataframe
print(tbl_df(lifeExp_80), n=nrows)
```

6. What 10 countries have the strongest correlation (in either direction) between life expectancy and per capita GDP?
```{R echo=TRUE, message=FALSE, warning=FALSE}
gapminder %>%
  group_by(country) %>%
  #To find high correlation in either direction I take the absolute value of the correlation
  summarise(correl=abs(cor(lifeExp, gdpPercap))) %>%
  arrange(desc(correl)) %>%
  head(10)
```

7. Which combinations of continent (besides Asia) and year have the highest average population across all countries? _N.b. your output should include all results sorted by highest average population_. With what you already know, this one may stump you. See [this Q&A](http://stackoverflow.com/q/27207963/654296) for how to `ungroup` before `arrange`ing. This also [behaves differently in more recent versions of dplyr](https://github.com/hadley/dplyr/releases/tag/v0.5.0).
```{R echo=TRUE, message=FALSE, warning=FALSE}
high_avg_pop=gapminder %>%
  filter(continent!="Asia") %>%
  group_by(continent, year) %>%
  summarise(avg_pop=mean(pop)) %>%
  ungroup() %>%
  arrange(desc(avg_pop)) 

nrows=nrow(high_avg_pop)

print(tbl_df(high_avg_pop), n=nrows)
```
Comparing it to the result _including_ Asia:
```{R echo=TRUE, message=FALSE, warning=FALSE}
high_avg_pop=gapminder %>%
  group_by(continent, year) %>%
  summarise(avg_pop=mean(pop)) %>%
  ungroup() %>%
  arrange(desc(avg_pop)) 

nrows=nrow(high_avg_pop)

print(tbl_df(high_avg_pop), n=nrows)
```

8. Which three countries have had the most consistent population estimates (i.e. lowest standard deviation) across the years of available data? 
```{R echo=TRUE, message=FALSE, warning=FALSE}
gapminder %>%
  group_by(country) %>%
  summarise(sd_pop=sd(pop)) %>%
  arrange(sd_pop) %>%
  head(3)
```

9. Subset **gm** to only include observations from 1992 and store the results as **gm1992**. What kind of object is this?
```{R echo=TRUE, message=FALSE, warning=FALSE}
gm1992=filter(gapminder, year==1992)
class(gm1992)
```
It is a data frame

10. Which observations indicate that the population of a country has *decreased* from the previous year **and** the life expectancy has *increased* from the previous year? See [the vignette on window functions](https://cran.r-project.org/web/packages/dplyr/vignettes/window-functions.html).
```{R echo=TRUE, message=FALSE, warning=FALSE}
changes=gapminder %>%
  group_by(country) %>% 
  arrange(country, year) %>% 
  mutate(chg_pop=pop-lag(pop), chg_lifeExp=lifeExp-lag(lifeExp)) %>%
  #Just to see an example of the changes, I keep two countries
  filter(country=="Argentina" | country=="Zimbabwe", !is.na(chg_pop), !is.na(chg_lifeExp)) %>%
  select(country, year, chg_pop, chg_lifeExp)

nrows=nrow(changes)
print(tbl_df(changes), n=nrows)
```
